#pragma once

namespace E6502
{
    enum Instructions
    {
        NOP    = 0xEA, // NO OPERATION
        LDA_IM = 0xA9, // LOAD ACCUMULATOR IMMEDIATE
        LDA_ZP = 0xA5, // LOAD ACCUMULATOR ZERO PAGE
        LDA_ZX = 0xB5, // LOAD ACCUMULATOR ZERO PAGE X
        LDA_AB = 0xAD, // LOAD ACCUMULATOR ABSOLUTE
        LDA_AX = 0xBD, // LOAD ACCUMULATOR ABSOLUTE X
        LDA_AY = 0xB9, // LOAD ACCUMULATOR ABSOLUTE y
        LDA_IX = 0xA1, // LOAD ACCUMULATOR INDIRECTED X
        LDA_IY = 0xB1, // LOAD ACCUMULATOR INDIRECTED Y
        LDX_IM = 0xA2, // LOAD INDEX REGISTER X IMMEDIATE
        LDX_ZP = 0xA6, // LOAD INDEX REGISTER X ZERO PAGE
        LDX_ZY = 0xB6, // LOAD INDEX REGISTER X ZERO PAGE Y
        LDX_AB = 0xAE, // LOAD INDEX REGISTER X ABSOLUTE
        LDX_AY = 0xBE, // LOAD INDEX REGISTER X ABSOLUTE Y
        LDY_IM = 0xA0, // LOAD INDEX REGISTER Y IMMEDIATE
        LDY_ZP = 0xA4, // LOAD INDEX REGISTER Y ZERO PAGE
        LDY_ZX = 0xB4, // LOAD INDEX REGISTER Y ZERO PAGE X
        LDY_AB = 0xAC, // LOAD INDEX REGISTER Y ABSOLUTE
        LDY_AX = 0xBC, // LOAD INDEX REGISTER Y ABSOLUTE X
        JMP_AB = 0x4C, // JUMP ABSOLUTE
        JSR    = 0x20, // JUMP TO SUBROUTINE
        RTS    = 0x60, // RETURN FROM SUBROUTINE
    };
}